//
//  NotificationsKey.swift
//  ForeeraApp
//


import Foundation

//Notification
let GOOGLEAPIKEY = "AIzaSyAgc6e93N7bil9v10idDEoHDpz7Oe6kuuI"
let GOOGEPLACEAPIKEY = "AIzaSyAgc6e93N7bil9v10idDEoHDpz7Oe6kuuI"
let kGCMMessageIDKey = "gcm.message_id";
let ENTRAMBITNOTIFICATIONKEY = "ENTRAMBITNOTIFICATIONKEY"

let CONVERNATENOTIFICATION = "CONVERNATENOTIFICATION"
let CONVERNATENOTIFICATIONI = "CONVERNATENOTIFICATIONI"

let ENTRAMBITFIRSTTIME = "ENTRAMBITFIRSTTIME"
let ENTRAMBITUSERLOGIN = "ENTRAMBITUSERLOGIN"
let ENTRAMBITUSERDATA = "ENTRAMBITUSERDATA"

//Choose City
let ENTRAMBITCHOOSECITY     = "ENTRAMBITCHOOSECITY"
let ENTRAMBITCHOOSECITYITEM = "ENTRAMBITCHOOSECITYITEM"

//address
let ENTRAMBITADDRESS     = "ENTRAMBITADDRESS"
let ENTRAMBITADDRESSITEM = "ENTRAMBITADDRESSITEM"

//Cart
let ENTRAMBITCARTDATA = "ENTRAMBITCARTDATA"
let ENTRAMBITCARTMEAL = "ENTRAMBITCARTMEAL"
let ENTRAMBITGOVERNATE = "ENTRAMBIGOVERNATE"
let fashionCart = "fachioncart"


//address--------------------------------
let ENTRAMBITUPDATEADDRESS    = "ENTRAMBITUPDATEADDRESS"
let ENTRAMBITGETADDRESS       = "ENTRAMBITGETADDRESS"
let ENTRAMBITGETADDRESSITEM   = "ENTRAMBITGETADDRESSITEM"
//-------------------------------------
//Date
let ENTRAMBITUPDATEDATE     = "ENTRAMBITUPDATEDATE"
let ENTRAMBITUPDATEDATEITEM = "ENTRAMBITUPDATEDATEITEM"
//
let ENTRAMBITUSERADDERRSTITLE   = "ENTRAMBITUSERADDERRSTITLE"
let ENTRAMBITUSERADDERRSID      =  "ENTRAMBITUSERADDERRSID"
//------
let ENTRAMBITPUSHNOTIFICATION   = "ENTRAMBITPUSHNOTIFICATION"
let ENTRAMBITPUSHNOTIFVIBRATION = "ENTRAMBITPUSHNOTIFVIBRATION"
let ENTRAMBITPUSHNOTIFSOUND     = "ENTRAMBITPUSHNOTIFSOUND"

//\\\\\\
let ENTRAMBITLOGOUTNOTI = "ENTRAMBITLOGOUTNOTI"

let RESTURANTID = "RESTURANTID"
let SaveArea = "SaveArea"
let SaveArea_Salon = "SaveAreaSalon"
let SaveType_Salon = "SaveTypeSalon"
let SaveDEpt_Salon = "SaveDeptSalon"

let ENTRAMBITGOVERNATESALON = "ENTRAMBIGOVERNATESALON"
let ENTRAMBISALONTYPE = "ENTRAMBISALONTYPE"
let ENTRAMBISALONDEPT = "ENTRAMBISALONDEPT"
